# Generated by Django 3.2.7 on 2021-09-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210929_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_photo_1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_photo_2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_photo_3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_photo_4',
        ),
    ]
